project_name_override: levro-codat
package_name_override: codat_api_client
use_path_prefixes_for_title_model_names: false
post_hooks:
   - "autoflake -i -r --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports ."
   - "isort ."
   - "black ."