""" Contains all the data models used in inputs/outputs """

from .codat_assess_data_contracts_account_categories_account_categories_model import (
    CodatAssessDataContractsAccountCategoriesAccountCategoriesModel,
)
from .codat_assess_data_contracts_account_categories_account_categories_model_paged_response_href_model import (
    CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseHrefModel,
)
from .codat_assess_data_contracts_account_categories_account_categories_model_paged_response_links_model import (
    CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseLinksModel,
)
from .codat_assess_data_contracts_account_categories_account_categories_model_paged_response_model import (
    CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseModel,
)
from .codat_assess_data_contracts_account_categories_account_category import (
    CodatAssessDataContractsAccountCategoriesAccountCategory,
)
from .codat_assess_data_contracts_account_categories_account_ref_model import (
    CodatAssessDataContractsAccountCategoriesAccountRefModel,
)
from .codat_assess_data_contracts_account_categories_confirmed_account_category_model import (
    CodatAssessDataContractsAccountCategoriesConfirmedAccountCategoryModel,
)
from .codat_assess_data_contracts_account_categories_patch_account_categories_model import (
    CodatAssessDataContractsAccountCategoriesPatchAccountCategoriesModel,
)
from .codat_assess_data_contracts_account_categories_patch_account_category_model import (
    CodatAssessDataContractsAccountCategoriesPatchAccountCategoryModel,
)
from .codat_assess_data_contracts_account_categories_patch_account_ref_model import (
    CodatAssessDataContractsAccountCategoriesPatchAccountRefModel,
)
from .codat_assess_data_contracts_account_categories_patch_single_account_category_model import (
    CodatAssessDataContractsAccountCategoriesPatchSingleAccountCategoryModel,
)
from .codat_assess_data_contracts_account_categories_suggested_account_category_model import (
    CodatAssessDataContractsAccountCategoriesSuggestedAccountCategoryModel,
)
from .codat_assess_data_contracts_cash_flow_transactions_accounts_data_source import (
    CodatAssessDataContractsCashFlowTransactionsAccountsDataSource,
)
from .codat_assess_data_contracts_cash_flow_transactions_cash_flow_report_banking_account import (
    CodatAssessDataContractsCashFlowTransactionsCashFlowReportBankingAccount,
)
from .codat_assess_data_contracts_cash_flow_transactions_cash_flow_report_banking_transaction import (
    CodatAssessDataContractsCashFlowTransactionsCashFlowReportBankingTransaction,
)
from .codat_assess_data_contracts_cash_flow_transactions_cash_flow_transactions_report import (
    CodatAssessDataContractsCashFlowTransactionsCashFlowTransactionsReport,
)
from .codat_assess_data_contracts_cash_flow_transactions_source_ref import (
    CodatAssessDataContractsCashFlowTransactionsSourceRef,
)
from .codat_assess_data_contracts_cash_flow_transactions_source_type import (
    CodatAssessDataContractsCashFlowTransactionsSourceType,
)
from .codat_assess_data_contracts_cash_flow_transactions_transaction_category import (
    CodatAssessDataContractsCashFlowTransactionsTransactionCategory,
)
from .codat_assess_data_contracts_cash_flow_transactions_transactions_data_source import (
    CodatAssessDataContractsCashFlowTransactionsTransactionsDataSource,
)
from .codat_assess_data_contracts_commerce_metrics_period_unit import CodatAssessDataContractsCommerceMetricsPeriodUnit
from .codat_assess_data_contracts_common_paged_report_info import CodatAssessDataContractsCommonPagedReportInfo
from .codat_assess_data_contracts_financials_metrics_financial_metrics_data_set import (
    CodatAssessDataContractsFinancialsMetricsFinancialMetricsDataSet,
)
from .codat_assess_data_contracts_financials_metrics_metric import CodatAssessDataContractsFinancialsMetricsMetric
from .codat_assess_data_contracts_financials_metrics_metric_data_set_error import (
    CodatAssessDataContractsFinancialsMetricsMetricDataSetError,
)
from .codat_assess_data_contracts_financials_metrics_metric_data_set_error_type import (
    CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorType,
)
from .codat_assess_data_contracts_financials_metrics_metric_error import (
    CodatAssessDataContractsFinancialsMetricsMetricError,
)
from .codat_assess_data_contracts_financials_metrics_metric_error_details import (
    CodatAssessDataContractsFinancialsMetricsMetricErrorDetails,
)
from .codat_assess_data_contracts_financials_metrics_metric_error_type import (
    CodatAssessDataContractsFinancialsMetricsMetricErrorType,
)
from .codat_assess_data_contracts_financials_metrics_metric_key import (
    CodatAssessDataContractsFinancialsMetricsMetricKey,
)
from .codat_assess_data_contracts_financials_metrics_metric_period import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriod,
)
from .codat_assess_data_contracts_financials_metrics_metric_period_error import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriodError,
)
from .codat_assess_data_contracts_financials_metrics_metric_period_error_details import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorDetails,
)
from .codat_assess_data_contracts_financials_metrics_metric_period_error_type import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorType,
)
from .codat_assess_data_contracts_financials_metrics_metric_period_input import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriodInput,
)
from .codat_assess_data_contracts_financials_metrics_metric_period_unit import (
    CodatAssessDataContractsFinancialsMetricsMetricPeriodUnit,
)
from .codat_assess_data_contracts_financials_metrics_metric_unit import (
    CodatAssessDataContractsFinancialsMetricsMetricUnit,
)
from .codat_assess_data_contracts_financials_statements_account_category import (
    CodatAssessDataContractsFinancialsStatementsAccountCategory,
)
from .codat_assess_data_contracts_financials_statements_account_category_level import (
    CodatAssessDataContractsFinancialsStatementsAccountCategoryLevel,
)
from .codat_assess_data_contracts_financials_statements_account_category_status import (
    CodatAssessDataContractsFinancialsStatementsAccountCategoryStatus,
)
from .codat_assess_data_contracts_financials_statements_enhanced_financial_statement import (
    CodatAssessDataContractsFinancialsStatementsEnhancedFinancialStatement,
)
from .codat_assess_data_contracts_financials_statements_financial_statement_report_info import (
    CodatAssessDataContractsFinancialsStatementsFinancialStatementReportInfo,
)
from .codat_assess_data_contracts_financials_statements_financial_statement_report_item import (
    CodatAssessDataContractsFinancialsStatementsFinancialStatementReportItem,
)
from .codat_clients_api_client_contract_client_sync_settings import CodatClientsApiClientContractClientSyncSettings
from .codat_clients_api_client_contract_company_settings import CodatClientsApiClientContractCompanySettings
from .codat_clients_api_client_contract_company_sync_settings import CodatClientsApiClientContractCompanySyncSettings
from .codat_clients_api_client_contract_sync_setting import CodatClientsApiClientContractSyncSetting
from .codat_data_contracts_datasets_account import CodatDataContractsDatasetsAccount
from .codat_data_contracts_datasets_account_paged_response_href_model import (
    CodatDataContractsDatasetsAccountPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_account_paged_response_links_model import (
    CodatDataContractsDatasetsAccountPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_account_paged_response_model import (
    CodatDataContractsDatasetsAccountPagedResponseModel,
)
from .codat_data_contracts_datasets_account_push_operation import CodatDataContractsDatasetsAccountPushOperation
from .codat_data_contracts_datasets_account_ref import CodatDataContractsDatasetsAccountRef
from .codat_data_contracts_datasets_account_status import CodatDataContractsDatasetsAccountStatus
from .codat_data_contracts_datasets_account_transaction import CodatDataContractsDatasetsAccountTransaction
from .codat_data_contracts_datasets_account_transaction_line import CodatDataContractsDatasetsAccountTransactionLine
from .codat_data_contracts_datasets_account_transaction_paged_response import (
    CodatDataContractsDatasetsAccountTransactionPagedResponse,
)
from .codat_data_contracts_datasets_account_transaction_paged_response_links import (
    CodatDataContractsDatasetsAccountTransactionPagedResponseLinks,
)
from .codat_data_contracts_datasets_account_transaction_status import CodatDataContractsDatasetsAccountTransactionStatus
from .codat_data_contracts_datasets_account_type import CodatDataContractsDatasetsAccountType
from .codat_data_contracts_datasets_accounts_payable_is_billed_to_type import (
    CodatDataContractsDatasetsAccountsPayableIsBilledToType,
)
from .codat_data_contracts_datasets_accounts_payable_tracking import CodatDataContractsDatasetsAccountsPayableTracking
from .codat_data_contracts_datasets_accounts_receivable_is_billed_to_type import (
    CodatDataContractsDatasetsAccountsReceivableIsBilledToType,
)
from .codat_data_contracts_datasets_accounts_receivable_tracking import (
    CodatDataContractsDatasetsAccountsReceivableTracking,
)
from .codat_data_contracts_datasets_address import CodatDataContractsDatasetsAddress
from .codat_data_contracts_datasets_address_type import CodatDataContractsDatasetsAddressType
from .codat_data_contracts_datasets_aged_creditor_outstanding import CodatDataContractsDatasetsAgedCreditorOutstanding
from .codat_data_contracts_datasets_aged_creditor_outstanding_i_collection_report import (
    CodatDataContractsDatasetsAgedCreditorOutstandingICollectionReport,
)
from .codat_data_contracts_datasets_aged_currency_outstanding import CodatDataContractsDatasetsAgedCurrencyOutstanding
from .codat_data_contracts_datasets_aged_debtor_outstanding import CodatDataContractsDatasetsAgedDebtorOutstanding
from .codat_data_contracts_datasets_aged_debtor_outstanding_i_collection_report import (
    CodatDataContractsDatasetsAgedDebtorOutstandingICollectionReport,
)
from .codat_data_contracts_datasets_aged_outstanding_amount import CodatDataContractsDatasetsAgedOutstandingAmount
from .codat_data_contracts_datasets_aged_outstanding_amount_detail import (
    CodatDataContractsDatasetsAgedOutstandingAmountDetail,
)
from .codat_data_contracts_datasets_allocation import CodatDataContractsDatasetsAllocation
from .codat_data_contracts_datasets_attachments_dataset import CodatDataContractsDatasetsAttachmentsDataset
from .codat_data_contracts_datasets_attachments_dataset_attachment import (
    CodatDataContractsDatasetsAttachmentsDatasetAttachment,
)
from .codat_data_contracts_datasets_balance_sheet import CodatDataContractsDatasetsBalanceSheet
from .codat_data_contracts_datasets_bank_account import CodatDataContractsDatasetsBankAccount
from .codat_data_contracts_datasets_bank_account_paged_response_href_model import (
    CodatDataContractsDatasetsBankAccountPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bank_account_paged_response_links_model import (
    CodatDataContractsDatasetsBankAccountPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bank_account_paged_response_model import (
    CodatDataContractsDatasetsBankAccountPagedResponseModel,
)
from .codat_data_contracts_datasets_bank_account_push_operation import (
    CodatDataContractsDatasetsBankAccountPushOperation,
)
from .codat_data_contracts_datasets_bank_account_type import CodatDataContractsDatasetsBankAccountType
from .codat_data_contracts_datasets_bank_statement_account import CodatDataContractsDatasetsBankStatementAccount
from .codat_data_contracts_datasets_bank_statement_line import CodatDataContractsDatasetsBankStatementLine
from .codat_data_contracts_datasets_bank_statement_line_paged_response_href_model import (
    CodatDataContractsDatasetsBankStatementLinePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bank_statement_line_paged_response_links_model import (
    CodatDataContractsDatasetsBankStatementLinePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bank_statement_line_paged_response_model import (
    CodatDataContractsDatasetsBankStatementLinePagedResponseModel,
)
from .codat_data_contracts_datasets_bank_transaction import CodatDataContractsDatasetsBankTransaction
from .codat_data_contracts_datasets_bank_transaction_paged_response_href_model import (
    CodatDataContractsDatasetsBankTransactionPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bank_transaction_paged_response_links_model import (
    CodatDataContractsDatasetsBankTransactionPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bank_transaction_paged_response_model import (
    CodatDataContractsDatasetsBankTransactionPagedResponseModel,
)
from .codat_data_contracts_datasets_bank_transactions import CodatDataContractsDatasetsBankTransactions
from .codat_data_contracts_datasets_bank_transactions_push_operation import (
    CodatDataContractsDatasetsBankTransactionsPushOperation,
)
from .codat_data_contracts_datasets_banking_account import CodatDataContractsDatasetsBankingAccount
from .codat_data_contracts_datasets_banking_account_balance import CodatDataContractsDatasetsBankingAccountBalance
from .codat_data_contracts_datasets_banking_account_balance_amounts import (
    CodatDataContractsDatasetsBankingAccountBalanceAmounts,
)
from .codat_data_contracts_datasets_banking_account_balance_paged_response_href_model import (
    CodatDataContractsDatasetsBankingAccountBalancePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_banking_account_balance_paged_response_links_model import (
    CodatDataContractsDatasetsBankingAccountBalancePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_banking_account_balance_paged_response_model import (
    CodatDataContractsDatasetsBankingAccountBalancePagedResponseModel,
)
from .codat_data_contracts_datasets_banking_account_identifiers import (
    CodatDataContractsDatasetsBankingAccountIdentifiers,
)
from .codat_data_contracts_datasets_banking_account_institution import (
    CodatDataContractsDatasetsBankingAccountInstitution,
)
from .codat_data_contracts_datasets_banking_account_paged_response_href_model import (
    CodatDataContractsDatasetsBankingAccountPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_banking_account_paged_response_links_model import (
    CodatDataContractsDatasetsBankingAccountPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_banking_account_paged_response_model import (
    CodatDataContractsDatasetsBankingAccountPagedResponseModel,
)
from .codat_data_contracts_datasets_banking_account_type import CodatDataContractsDatasetsBankingAccountType
from .codat_data_contracts_datasets_banking_banking_transaction_code import (
    CodatDataContractsDatasetsBankingBankingTransactionCode,
)
from .codat_data_contracts_datasets_banking_transaction import CodatDataContractsDatasetsBankingTransaction
from .codat_data_contracts_datasets_banking_transaction_category import (
    CodatDataContractsDatasetsBankingTransactionCategory,
)
from .codat_data_contracts_datasets_banking_transaction_category_paged_response_href_model import (
    CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_banking_transaction_category_paged_response_links_model import (
    CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_banking_transaction_category_paged_response_model import (
    CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseModel,
)
from .codat_data_contracts_datasets_banking_transaction_category_ref import (
    CodatDataContractsDatasetsBankingTransactionCategoryRef,
)
from .codat_data_contracts_datasets_banking_transaction_category_status import (
    CodatDataContractsDatasetsBankingTransactionCategoryStatus,
)
from .codat_data_contracts_datasets_banking_transaction_paged_response_href_model import (
    CodatDataContractsDatasetsBankingTransactionPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_banking_transaction_paged_response_links_model import (
    CodatDataContractsDatasetsBankingTransactionPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_banking_transaction_paged_response_model import (
    CodatDataContractsDatasetsBankingTransactionPagedResponseModel,
)
from .codat_data_contracts_datasets_bill import CodatDataContractsDatasetsBill
from .codat_data_contracts_datasets_bill_credit_note import CodatDataContractsDatasetsBillCreditNote
from .codat_data_contracts_datasets_bill_credit_note_line_item import CodatDataContractsDatasetsBillCreditNoteLineItem
from .codat_data_contracts_datasets_bill_credit_note_paged_response_href_model import (
    CodatDataContractsDatasetsBillCreditNotePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bill_credit_note_paged_response_links_model import (
    CodatDataContractsDatasetsBillCreditNotePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bill_credit_note_paged_response_model import (
    CodatDataContractsDatasetsBillCreditNotePagedResponseModel,
)
from .codat_data_contracts_datasets_bill_credit_note_push_operation import (
    CodatDataContractsDatasetsBillCreditNotePushOperation,
)
from .codat_data_contracts_datasets_bill_item import CodatDataContractsDatasetsBillItem
from .codat_data_contracts_datasets_bill_line_item import CodatDataContractsDatasetsBillLineItem
from .codat_data_contracts_datasets_bill_paged_response_href_model import (
    CodatDataContractsDatasetsBillPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bill_paged_response_links_model import (
    CodatDataContractsDatasetsBillPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bill_paged_response_model import CodatDataContractsDatasetsBillPagedResponseModel
from .codat_data_contracts_datasets_bill_payment import CodatDataContractsDatasetsBillPayment
from .codat_data_contracts_datasets_bill_payment_line import CodatDataContractsDatasetsBillPaymentLine
from .codat_data_contracts_datasets_bill_payment_line_link import CodatDataContractsDatasetsBillPaymentLineLink
from .codat_data_contracts_datasets_bill_payment_link_type import CodatDataContractsDatasetsBillPaymentLinkType
from .codat_data_contracts_datasets_bill_payment_paged_response_href_model import (
    CodatDataContractsDatasetsBillPaymentPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_bill_payment_paged_response_links_model import (
    CodatDataContractsDatasetsBillPaymentPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_bill_payment_paged_response_model import (
    CodatDataContractsDatasetsBillPaymentPagedResponseModel,
)
from .codat_data_contracts_datasets_bill_payment_push_operation import (
    CodatDataContractsDatasetsBillPaymentPushOperation,
)
from .codat_data_contracts_datasets_bill_push_operation import CodatDataContractsDatasetsBillPushOperation
from .codat_data_contracts_datasets_bill_status import CodatDataContractsDatasetsBillStatus
from .codat_data_contracts_datasets_cash_flow_statement import CodatDataContractsDatasetsCashFlowStatement
from .codat_data_contracts_datasets_cash_flow_statement_reporting_basis import (
    CodatDataContractsDatasetsCashFlowStatementReportingBasis,
)
from .codat_data_contracts_datasets_cash_flow_statement_reporting_data import (
    CodatDataContractsDatasetsCashFlowStatementReportingData,
)
from .codat_data_contracts_datasets_commerce_account_balance import CodatDataContractsDatasetsCommerceAccountBalance
from .codat_data_contracts_datasets_commerce_address import CodatDataContractsDatasetsCommerceAddress
from .codat_data_contracts_datasets_commerce_address_type import CodatDataContractsDatasetsCommerceAddressType
from .codat_data_contracts_datasets_commerce_ancestor_ref import CodatDataContractsDatasetsCommerceAncestorRef
from .codat_data_contracts_datasets_commerce_company_info import CodatDataContractsDatasetsCommerceCompanyInfo
from .codat_data_contracts_datasets_commerce_company_info_source_urls import (
    CodatDataContractsDatasetsCommerceCompanyInfoSourceUrls,
)
from .codat_data_contracts_datasets_commerce_customer import CodatDataContractsDatasetsCommerceCustomer
from .codat_data_contracts_datasets_commerce_customer_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceCustomerPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_customer_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceCustomerPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_customer_paged_response_model import (
    CodatDataContractsDatasetsCommerceCustomerPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_customer_ref import CodatDataContractsDatasetsCommerceCustomerRef
from .codat_data_contracts_datasets_commerce_discount_allocation import (
    CodatDataContractsDatasetsCommerceDiscountAllocation,
)
from .codat_data_contracts_datasets_commerce_dispute import CodatDataContractsDatasetsCommerceDispute
from .codat_data_contracts_datasets_commerce_dispute_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceDisputePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_dispute_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceDisputePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_dispute_paged_response_model import (
    CodatDataContractsDatasetsCommerceDisputePagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_dispute_status import CodatDataContractsDatasetsCommerceDisputeStatus
from .codat_data_contracts_datasets_commerce_inventory import CodatDataContractsDatasetsCommerceInventory
from .codat_data_contracts_datasets_commerce_inventory_location import (
    CodatDataContractsDatasetsCommerceInventoryLocation,
)
from .codat_data_contracts_datasets_commerce_location import CodatDataContractsDatasetsCommerceLocation
from .codat_data_contracts_datasets_commerce_location_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceLocationPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_location_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceLocationPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_location_paged_response_model import (
    CodatDataContractsDatasetsCommerceLocationPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_location_ref import CodatDataContractsDatasetsCommerceLocationRef
from .codat_data_contracts_datasets_commerce_order import CodatDataContractsDatasetsCommerceOrder
from .codat_data_contracts_datasets_commerce_order_line_item import CodatDataContractsDatasetsCommerceOrderLineItem
from .codat_data_contracts_datasets_commerce_order_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceOrderPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_order_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceOrderPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_order_paged_response_model import (
    CodatDataContractsDatasetsCommerceOrderPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_payment import CodatDataContractsDatasetsCommercePayment
from .codat_data_contracts_datasets_commerce_payment_method import CodatDataContractsDatasetsCommercePaymentMethod
from .codat_data_contracts_datasets_commerce_payment_method_paged_response_href_model import (
    CodatDataContractsDatasetsCommercePaymentMethodPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_payment_method_paged_response_links_model import (
    CodatDataContractsDatasetsCommercePaymentMethodPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_payment_method_paged_response_model import (
    CodatDataContractsDatasetsCommercePaymentMethodPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_payment_method_ref import (
    CodatDataContractsDatasetsCommercePaymentMethodRef,
)
from .codat_data_contracts_datasets_commerce_payment_method_status import (
    CodatDataContractsDatasetsCommercePaymentMethodStatus,
)
from .codat_data_contracts_datasets_commerce_payment_paged_response_href_model import (
    CodatDataContractsDatasetsCommercePaymentPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_payment_paged_response_links_model import (
    CodatDataContractsDatasetsCommercePaymentPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_payment_paged_response_model import (
    CodatDataContractsDatasetsCommercePaymentPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_payment_ref import CodatDataContractsDatasetsCommercePaymentRef
from .codat_data_contracts_datasets_commerce_payment_status import CodatDataContractsDatasetsCommercePaymentStatus
from .codat_data_contracts_datasets_commerce_payment_type import CodatDataContractsDatasetsCommercePaymentType
from .codat_data_contracts_datasets_commerce_phone import CodatDataContractsDatasetsCommercePhone
from .codat_data_contracts_datasets_commerce_phone_type import CodatDataContractsDatasetsCommercePhoneType
from .codat_data_contracts_datasets_commerce_platform_transaction_type import (
    CodatDataContractsDatasetsCommercePlatformTransactionType,
)
from .codat_data_contracts_datasets_commerce_product import CodatDataContractsDatasetsCommerceProduct
from .codat_data_contracts_datasets_commerce_product_category import CodatDataContractsDatasetsCommerceProductCategory
from .codat_data_contracts_datasets_commerce_product_category_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceProductCategoryPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_product_category_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceProductCategoryPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_product_category_paged_response_model import (
    CodatDataContractsDatasetsCommerceProductCategoryPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_product_category_ref import (
    CodatDataContractsDatasetsCommerceProductCategoryRef,
)
from .codat_data_contracts_datasets_commerce_product_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceProductPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_product_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceProductPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_product_paged_response_model import (
    CodatDataContractsDatasetsCommerceProductPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_product_ref import CodatDataContractsDatasetsCommerceProductRef
from .codat_data_contracts_datasets_commerce_product_status import CodatDataContractsDatasetsCommerceProductStatus
from .codat_data_contracts_datasets_commerce_product_variant import CodatDataContractsDatasetsCommerceProductVariant
from .codat_data_contracts_datasets_commerce_product_variant_price import (
    CodatDataContractsDatasetsCommerceProductVariantPrice,
)
from .codat_data_contracts_datasets_commerce_service_charge import CodatDataContractsDatasetsCommerceServiceCharge
from .codat_data_contracts_datasets_commerce_service_charge_type import (
    CodatDataContractsDatasetsCommerceServiceChargeType,
)
from .codat_data_contracts_datasets_commerce_tax_component_allocation import (
    CodatDataContractsDatasetsCommerceTaxComponentAllocation,
)
from .codat_data_contracts_datasets_commerce_tax_component_ref import CodatDataContractsDatasetsCommerceTaxComponentRef
from .codat_data_contracts_datasets_commerce_transaction import CodatDataContractsDatasetsCommerceTransaction
from .codat_data_contracts_datasets_commerce_transaction_paged_response_href_model import (
    CodatDataContractsDatasetsCommerceTransactionPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_commerce_transaction_paged_response_links_model import (
    CodatDataContractsDatasetsCommerceTransactionPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_commerce_transaction_paged_response_model import (
    CodatDataContractsDatasetsCommerceTransactionPagedResponseModel,
)
from .codat_data_contracts_datasets_commerce_transaction_ref_type import (
    CodatDataContractsDatasetsCommerceTransactionRefType,
)
from .codat_data_contracts_datasets_commerce_transaction_source_ref import (
    CodatDataContractsDatasetsCommerceTransactionSourceRef,
)
from .codat_data_contracts_datasets_commerce_web_link import CodatDataContractsDatasetsCommerceWebLink
from .codat_data_contracts_datasets_commerce_web_link_type import CodatDataContractsDatasetsCommerceWebLinkType
from .codat_data_contracts_datasets_company_dataset import CodatDataContractsDatasetsCompanyDataset
from .codat_data_contracts_datasets_company_dataset_source_urls import (
    CodatDataContractsDatasetsCompanyDatasetSourceUrls,
)
from .codat_data_contracts_datasets_contact import CodatDataContractsDatasetsContact
from .codat_data_contracts_datasets_contact_ref import CodatDataContractsDatasetsContactRef
from .codat_data_contracts_datasets_credit_note import CodatDataContractsDatasetsCreditNote
from .codat_data_contracts_datasets_credit_note_line_item import CodatDataContractsDatasetsCreditNoteLineItem
from .codat_data_contracts_datasets_credit_note_paged_response_href_model import (
    CodatDataContractsDatasetsCreditNotePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_credit_note_paged_response_links_model import (
    CodatDataContractsDatasetsCreditNotePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_credit_note_paged_response_model import (
    CodatDataContractsDatasetsCreditNotePagedResponseModel,
)
from .codat_data_contracts_datasets_credit_note_push_operation import CodatDataContractsDatasetsCreditNotePushOperation
from .codat_data_contracts_datasets_credit_note_status import CodatDataContractsDatasetsCreditNoteStatus
from .codat_data_contracts_datasets_customer import CodatDataContractsDatasetsCustomer
from .codat_data_contracts_datasets_customer_paged_response_href_model import (
    CodatDataContractsDatasetsCustomerPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_customer_paged_response_links_model import (
    CodatDataContractsDatasetsCustomerPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_customer_paged_response_model import (
    CodatDataContractsDatasetsCustomerPagedResponseModel,
)
from .codat_data_contracts_datasets_customer_push_operation import CodatDataContractsDatasetsCustomerPushOperation
from .codat_data_contracts_datasets_customer_ref import CodatDataContractsDatasetsCustomerRef
from .codat_data_contracts_datasets_customer_status import CodatDataContractsDatasetsCustomerStatus
from .codat_data_contracts_datasets_data_interfaces_supplemental_data import (
    CodatDataContractsDatasetsDataInterfacesSupplementalData,
)
from .codat_data_contracts_datasets_data_interfaces_supplemental_data_content import (
    CodatDataContractsDatasetsDataInterfacesSupplementalDataContent,
)
from .codat_data_contracts_datasets_data_interfaces_supplemental_data_content_additional_property import (
    CodatDataContractsDatasetsDataInterfacesSupplementalDataContentAdditionalProperty,
)
from .codat_data_contracts_datasets_detailed_payment_allocation import (
    CodatDataContractsDatasetsDetailedPaymentAllocation,
)
from .codat_data_contracts_datasets_direct_cost import CodatDataContractsDatasetsDirectCost
from .codat_data_contracts_datasets_direct_cost_line_item import CodatDataContractsDatasetsDirectCostLineItem
from .codat_data_contracts_datasets_direct_cost_paged_response_href_model import (
    CodatDataContractsDatasetsDirectCostPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_direct_cost_paged_response_links_model import (
    CodatDataContractsDatasetsDirectCostPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_direct_cost_paged_response_model import (
    CodatDataContractsDatasetsDirectCostPagedResponseModel,
)
from .codat_data_contracts_datasets_direct_cost_push_operation import CodatDataContractsDatasetsDirectCostPushOperation
from .codat_data_contracts_datasets_direct_income import CodatDataContractsDatasetsDirectIncome
from .codat_data_contracts_datasets_direct_income_line_item import CodatDataContractsDatasetsDirectIncomeLineItem
from .codat_data_contracts_datasets_direct_income_paged_response_href_model import (
    CodatDataContractsDatasetsDirectIncomePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_direct_income_paged_response_links_model import (
    CodatDataContractsDatasetsDirectIncomePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_direct_income_paged_response_model import (
    CodatDataContractsDatasetsDirectIncomePagedResponseModel,
)
from .codat_data_contracts_datasets_direct_income_push_operation import (
    CodatDataContractsDatasetsDirectIncomePushOperation,
)
from .codat_data_contracts_datasets_from_account import CodatDataContractsDatasetsFromAccount
from .codat_data_contracts_datasets_invoice import CodatDataContractsDatasetsInvoice
from .codat_data_contracts_datasets_invoice_item import CodatDataContractsDatasetsInvoiceItem
from .codat_data_contracts_datasets_invoice_line_item import CodatDataContractsDatasetsInvoiceLineItem
from .codat_data_contracts_datasets_invoice_paged_response_href_model import (
    CodatDataContractsDatasetsInvoicePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_invoice_paged_response_links_model import (
    CodatDataContractsDatasetsInvoicePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_invoice_paged_response_model import (
    CodatDataContractsDatasetsInvoicePagedResponseModel,
)
from .codat_data_contracts_datasets_invoice_push_operation import CodatDataContractsDatasetsInvoicePushOperation
from .codat_data_contracts_datasets_invoice_status import CodatDataContractsDatasetsInvoiceStatus
from .codat_data_contracts_datasets_invoiceable_tracking import CodatDataContractsDatasetsInvoiceableTracking
from .codat_data_contracts_datasets_invoicing_status import CodatDataContractsDatasetsInvoicingStatus
from .codat_data_contracts_datasets_item import CodatDataContractsDatasetsItem
from .codat_data_contracts_datasets_item_paged_response_href_model import (
    CodatDataContractsDatasetsItemPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_item_paged_response_links_model import (
    CodatDataContractsDatasetsItemPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_item_paged_response_model import CodatDataContractsDatasetsItemPagedResponseModel
from .codat_data_contracts_datasets_item_push_operation import CodatDataContractsDatasetsItemPushOperation
from .codat_data_contracts_datasets_item_ref import CodatDataContractsDatasetsItemRef
from .codat_data_contracts_datasets_item_status import CodatDataContractsDatasetsItemStatus
from .codat_data_contracts_datasets_item_type import CodatDataContractsDatasetsItemType
from .codat_data_contracts_datasets_journal import CodatDataContractsDatasetsJournal
from .codat_data_contracts_datasets_journal_entry import CodatDataContractsDatasetsJournalEntry
from .codat_data_contracts_datasets_journal_entry_paged_response_href_model import (
    CodatDataContractsDatasetsJournalEntryPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_journal_entry_paged_response_links_model import (
    CodatDataContractsDatasetsJournalEntryPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_journal_entry_paged_response_model import (
    CodatDataContractsDatasetsJournalEntryPagedResponseModel,
)
from .codat_data_contracts_datasets_journal_entry_push_operation import (
    CodatDataContractsDatasetsJournalEntryPushOperation,
)
from .codat_data_contracts_datasets_journal_line import CodatDataContractsDatasetsJournalLine
from .codat_data_contracts_datasets_journal_paged_response_href_model import (
    CodatDataContractsDatasetsJournalPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_journal_paged_response_links_model import (
    CodatDataContractsDatasetsJournalPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_journal_paged_response_model import (
    CodatDataContractsDatasetsJournalPagedResponseModel,
)
from .codat_data_contracts_datasets_journal_push_operation import CodatDataContractsDatasetsJournalPushOperation
from .codat_data_contracts_datasets_journal_ref import CodatDataContractsDatasetsJournalRef
from .codat_data_contracts_datasets_journal_status import CodatDataContractsDatasetsJournalStatus
from .codat_data_contracts_datasets_metadata import CodatDataContractsDatasetsMetadata
from .codat_data_contracts_datasets_payment import CodatDataContractsDatasetsPayment
from .codat_data_contracts_datasets_payment_allocation_payment import CodatDataContractsDatasetsPaymentAllocationPayment
from .codat_data_contracts_datasets_payment_line import CodatDataContractsDatasetsPaymentLine
from .codat_data_contracts_datasets_payment_line_link import CodatDataContractsDatasetsPaymentLineLink
from .codat_data_contracts_datasets_payment_link_type import CodatDataContractsDatasetsPaymentLinkType
from .codat_data_contracts_datasets_payment_method import CodatDataContractsDatasetsPaymentMethod
from .codat_data_contracts_datasets_payment_method_paged_response_href_model import (
    CodatDataContractsDatasetsPaymentMethodPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_payment_method_paged_response_links_model import (
    CodatDataContractsDatasetsPaymentMethodPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_payment_method_paged_response_model import (
    CodatDataContractsDatasetsPaymentMethodPagedResponseModel,
)
from .codat_data_contracts_datasets_payment_method_ref import CodatDataContractsDatasetsPaymentMethodRef
from .codat_data_contracts_datasets_payment_method_status import CodatDataContractsDatasetsPaymentMethodStatus
from .codat_data_contracts_datasets_payment_method_type import CodatDataContractsDatasetsPaymentMethodType
from .codat_data_contracts_datasets_payment_paged_response_href_model import (
    CodatDataContractsDatasetsPaymentPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_payment_paged_response_links_model import (
    CodatDataContractsDatasetsPaymentPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_payment_paged_response_model import (
    CodatDataContractsDatasetsPaymentPagedResponseModel,
)
from .codat_data_contracts_datasets_payment_push_operation import CodatDataContractsDatasetsPaymentPushOperation
from .codat_data_contracts_datasets_phone import CodatDataContractsDatasetsPhone
from .codat_data_contracts_datasets_phone_type import CodatDataContractsDatasetsPhoneType
from .codat_data_contracts_datasets_profit_and_loss_report import CodatDataContractsDatasetsProfitAndLossReport
from .codat_data_contracts_datasets_profit_and_loss_reporting_type import (
    CodatDataContractsDatasetsProfitAndLossReportingType,
)
from .codat_data_contracts_datasets_project_ref import CodatDataContractsDatasetsProjectRef
from .codat_data_contracts_datasets_purchase_order import CodatDataContractsDatasetsPurchaseOrder
from .codat_data_contracts_datasets_purchase_order_line_item import CodatDataContractsDatasetsPurchaseOrderLineItem
from .codat_data_contracts_datasets_purchase_order_paged_response_href_model import (
    CodatDataContractsDatasetsPurchaseOrderPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_purchase_order_paged_response_links_model import (
    CodatDataContractsDatasetsPurchaseOrderPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_purchase_order_paged_response_model import (
    CodatDataContractsDatasetsPurchaseOrderPagedResponseModel,
)
from .codat_data_contracts_datasets_purchase_order_push_operation import (
    CodatDataContractsDatasetsPurchaseOrderPushOperation,
)
from .codat_data_contracts_datasets_purchase_order_ref import CodatDataContractsDatasetsPurchaseOrderRef
from .codat_data_contracts_datasets_purchase_order_status import CodatDataContractsDatasetsPurchaseOrderStatus
from .codat_data_contracts_datasets_record_ref import CodatDataContractsDatasetsRecordRef
from .codat_data_contracts_datasets_report_line import CodatDataContractsDatasetsReportLine
from .codat_data_contracts_datasets_sales_order import CodatDataContractsDatasetsSalesOrder
from .codat_data_contracts_datasets_sales_order_line_item import CodatDataContractsDatasetsSalesOrderLineItem
from .codat_data_contracts_datasets_sales_order_paged_response_href_model import (
    CodatDataContractsDatasetsSalesOrderPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_sales_order_paged_response_links_model import (
    CodatDataContractsDatasetsSalesOrderPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_sales_order_paged_response_model import (
    CodatDataContractsDatasetsSalesOrderPagedResponseModel,
)
from .codat_data_contracts_datasets_sales_order_status import CodatDataContractsDatasetsSalesOrderStatus
from .codat_data_contracts_datasets_ship_to import CodatDataContractsDatasetsShipTo
from .codat_data_contracts_datasets_ship_to_contact import CodatDataContractsDatasetsShipToContact
from .codat_data_contracts_datasets_supplier import CodatDataContractsDatasetsSupplier
from .codat_data_contracts_datasets_supplier_paged_response_href_model import (
    CodatDataContractsDatasetsSupplierPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_supplier_paged_response_links_model import (
    CodatDataContractsDatasetsSupplierPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_supplier_paged_response_model import (
    CodatDataContractsDatasetsSupplierPagedResponseModel,
)
from .codat_data_contracts_datasets_supplier_push_operation import CodatDataContractsDatasetsSupplierPushOperation
from .codat_data_contracts_datasets_supplier_ref import CodatDataContractsDatasetsSupplierRef
from .codat_data_contracts_datasets_supplier_status import CodatDataContractsDatasetsSupplierStatus
from .codat_data_contracts_datasets_tax_rate import CodatDataContractsDatasetsTaxRate
from .codat_data_contracts_datasets_tax_rate_component import CodatDataContractsDatasetsTaxRateComponent
from .codat_data_contracts_datasets_tax_rate_paged_response_href_model import (
    CodatDataContractsDatasetsTaxRatePagedResponseHrefModel,
)
from .codat_data_contracts_datasets_tax_rate_paged_response_links_model import (
    CodatDataContractsDatasetsTaxRatePagedResponseLinksModel,
)
from .codat_data_contracts_datasets_tax_rate_paged_response_model import (
    CodatDataContractsDatasetsTaxRatePagedResponseModel,
)
from .codat_data_contracts_datasets_tax_rate_ref import CodatDataContractsDatasetsTaxRateRef
from .codat_data_contracts_datasets_tax_rate_status import CodatDataContractsDatasetsTaxRateStatus
from .codat_data_contracts_datasets_to_account import CodatDataContractsDatasetsToAccount
from .codat_data_contracts_datasets_tracking import CodatDataContractsDatasetsTracking
from .codat_data_contracts_datasets_tracking_category_ref import CodatDataContractsDatasetsTrackingCategoryRef
from .codat_data_contracts_datasets_tracking_category_status import CodatDataContractsDatasetsTrackingCategoryStatus
from .codat_data_contracts_datasets_transaction_type import CodatDataContractsDatasetsTransactionType
from .codat_data_contracts_datasets_transfer import CodatDataContractsDatasetsTransfer
from .codat_data_contracts_datasets_transfer_paged_response_href_model import (
    CodatDataContractsDatasetsTransferPagedResponseHrefModel,
)
from .codat_data_contracts_datasets_transfer_paged_response_links_model import (
    CodatDataContractsDatasetsTransferPagedResponseLinksModel,
)
from .codat_data_contracts_datasets_transfer_paged_response_model import (
    CodatDataContractsDatasetsTransferPagedResponseModel,
)
from .codat_data_contracts_datasets_transfer_push_operation import CodatDataContractsDatasetsTransferPushOperation
from .codat_data_contracts_datasets_transfer_status import CodatDataContractsDatasetsTransferStatus
from .codat_data_contracts_datasets_valid_datatype_links import CodatDataContractsDatasetsValidDatatypeLinks
from .codat_data_contracts_datasets_web_link import CodatDataContractsDatasetsWebLink
from .codat_data_contracts_datasets_web_link_type import CodatDataContractsDatasetsWebLinkType
from .codat_data_contracts_datasets_withholding_tax import CodatDataContractsDatasetsWithholdingTax
from .codat_data_contracts_push_option_type import CodatDataContractsPushOptionType
from .codat_data_contracts_push_push_change_type import CodatDataContractsPushPushChangeType
from .codat_data_contracts_push_push_field_validation import CodatDataContractsPushPushFieldValidation
from .codat_data_contracts_push_push_operation_change import CodatDataContractsPushPushOperationChange
from .codat_data_contracts_push_push_operation_record_ref import CodatDataContractsPushPushOperationRecordRef
from .codat_data_contracts_push_push_option import CodatDataContractsPushPushOption
from .codat_data_contracts_push_push_option_choice import CodatDataContractsPushPushOptionChoice
from .codat_data_contracts_push_push_option_choice_properties import CodatDataContractsPushPushOptionChoiceProperties
from .codat_data_contracts_push_push_option_properties import CodatDataContractsPushPushOptionProperties
from .codat_data_contracts_push_push_validation_info import CodatDataContractsPushPushValidationInfo
from .codat_data_contracts_responses_hal_link import CodatDataContractsResponsesHalLink
from .codat_data_contracts_validation_validation_item import CodatDataContractsValidationValidationItem
from .codat_data_contracts_validation_validation_result import CodatDataContractsValidationValidationResult
from .codat_data_integrity_contracts_details_transaction_details import (
    CodatDataIntegrityContractsDetailsTransactionDetails,
)
from .codat_data_integrity_contracts_details_transaction_details_paged_response import (
    CodatDataIntegrityContractsDetailsTransactionDetailsPagedResponse,
)
from .codat_data_integrity_contracts_details_transaction_details_paged_response_links import (
    CodatDataIntegrityContractsDetailsTransactionDetailsPagedResponseLinks,
)
from .codat_data_integrity_contracts_metadata_match_amount_info import (
    CodatDataIntegrityContractsMetadataMatchAmountInfo,
)
from .codat_data_integrity_contracts_metadata_match_connection_ids import (
    CodatDataIntegrityContractsMetadataMatchConnectionIds,
)
from .codat_data_integrity_contracts_metadata_match_date_info import CodatDataIntegrityContractsMetadataMatchDateInfo
from .codat_data_integrity_contracts_metadata_match_metadata import CodatDataIntegrityContractsMetadataMatchMetadata
from .codat_data_integrity_contracts_metadata_match_metadata_response import (
    CodatDataIntegrityContractsMetadataMatchMetadataResponse,
)
from .codat_data_integrity_contracts_metadata_match_status_info import (
    CodatDataIntegrityContractsMetadataMatchStatusInfo,
)
from .codat_data_integrity_contracts_metadata_run_status import CodatDataIntegrityContractsMetadataRunStatus
from .codat_data_integrity_contracts_summary_match_amount_summary import (
    CodatDataIntegrityContractsSummaryMatchAmountSummary,
)
from .codat_data_integrity_contracts_summary_match_count_summary import (
    CodatDataIntegrityContractsSummaryMatchCountSummary,
)
from .codat_data_integrity_contracts_summary_match_summaries_response import (
    CodatDataIntegrityContractsSummaryMatchSummariesResponse,
)
from .codat_data_integrity_contracts_summary_match_summary import CodatDataIntegrityContractsSummaryMatchSummary
from .codat_public_api_models_assess_assess_excel_meta import CodatPublicApiModelsAssessAssessExcelMeta
from .codat_public_api_models_clients_banking_settings_models_bank_integration import (
    CodatPublicApiModelsClientsBankingSettingsModelsBankIntegration,
)
from .codat_public_api_models_clients_banking_settings_models_bank_setting import (
    CodatPublicApiModelsClientsBankingSettingsModelsBankSetting,
)
from .codat_public_api_models_clients_banking_settings_models_bank_settings_dataset import (
    CodatPublicApiModelsClientsBankingSettingsModelsBankSettingsDataset,
)
from .codat_public_api_models_clients_client_company_metrics_model import (
    CodatPublicApiModelsClientsClientCompanyMetricsModel,
)
from .codat_public_api_models_clients_client_settings_model import CodatPublicApiModelsClientsClientSettingsModel
from .codat_public_api_models_clients_client_settings_patch_model import (
    CodatPublicApiModelsClientsClientSettingsPatchModel,
)
from .codat_public_api_models_clients_client_sync_settings_model import (
    CodatPublicApiModelsClientsClientSyncSettingsModel,
)
from .codat_public_api_models_clients_client_sync_settings_single_put_model import (
    CodatPublicApiModelsClientsClientSyncSettingsSinglePutModel,
)
from .codat_public_api_models_clients_integration_branding_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModel,
)
from .codat_public_api_models_clients_integration_branding_model_button_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelButtonModel,
)
from .codat_public_api_models_clients_integration_branding_model_default_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelDefaultModel,
)
from .codat_public_api_models_clients_integration_branding_model_full_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelFullModel,
)
from .codat_public_api_models_clients_integration_branding_model_hover_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelHoverModel,
)
from .codat_public_api_models_clients_integration_branding_model_image_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelImageModel,
)
from .codat_public_api_models_clients_integration_branding_model_logo_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel,
)
from .codat_public_api_models_clients_integration_branding_model_square_model import (
    CodatPublicApiModelsClientsIntegrationBrandingModelSquareModel,
)
from .codat_public_api_models_clients_integration_settings_model import (
    CodatPublicApiModelsClientsIntegrationSettingsModel,
)
from .codat_public_api_models_clients_integration_settings_patch_model import (
    CodatPublicApiModelsClientsIntegrationSettingsPatchModel,
)
from .codat_public_api_models_company_add_company_model import CodatPublicApiModelsCompanyAddCompanyModel
from .codat_public_api_models_company_company import CodatPublicApiModelsCompanyCompany
from .codat_public_api_models_company_company_event_stream import CodatPublicApiModelsCompanyCompanyEventStream
from .codat_public_api_models_company_company_event_stream_item import CodatPublicApiModelsCompanyCompanyEventStreamItem
from .codat_public_api_models_company_company_paged_response_href_model import (
    CodatPublicApiModelsCompanyCompanyPagedResponseHrefModel,
)
from .codat_public_api_models_company_company_paged_response_links_model import (
    CodatPublicApiModelsCompanyCompanyPagedResponseLinksModel,
)
from .codat_public_api_models_company_company_paged_response_model import (
    CodatPublicApiModelsCompanyCompanyPagedResponseModel,
)
from .codat_public_api_models_company_company_settings import CodatPublicApiModelsCompanyCompanySettings
from .codat_public_api_models_company_data_connection import CodatPublicApiModelsCompanyDataConnection
from .codat_public_api_models_company_data_connection_connection_info import (
    CodatPublicApiModelsCompanyDataConnectionConnectionInfo,
)
from .codat_public_api_models_company_data_connection_error import CodatPublicApiModelsCompanyDataConnectionError
from .codat_public_api_models_company_data_connection_paged_response_href_model import (
    CodatPublicApiModelsCompanyDataConnectionPagedResponseHrefModel,
)
from .codat_public_api_models_company_data_connection_paged_response_links_model import (
    CodatPublicApiModelsCompanyDataConnectionPagedResponseLinksModel,
)
from .codat_public_api_models_company_data_connection_paged_response_model import (
    CodatPublicApiModelsCompanyDataConnectionPagedResponseModel,
)
from .codat_public_api_models_company_patch_data_connection_model import (
    CodatPublicApiModelsCompanyPatchDataConnectionModel,
)
from .codat_public_api_models_company_patch_data_connection_model_connection_info import (
    CodatPublicApiModelsCompanyPatchDataConnectionModelConnectionInfo,
)
from .codat_public_api_models_company_profile_model import CodatPublicApiModelsCompanyProfileModel
from .codat_public_api_models_company_update_company_model import CodatPublicApiModelsCompanyUpdateCompanyModel
from .codat_public_api_models_data_account_response import CodatPublicApiModelsDataAccountResponse
from .codat_public_api_models_data_account_status_response import CodatPublicApiModelsDataAccountStatusResponse
from .codat_public_api_models_data_account_type_response import CodatPublicApiModelsDataAccountTypeResponse
from .codat_public_api_models_data_balance_sheet_response import CodatPublicApiModelsDataBalanceSheetResponse
from .codat_public_api_models_data_cash_flow_statement_response import CodatPublicApiModelsDataCashFlowStatementResponse
from .codat_public_api_models_data_data_set import CodatPublicApiModelsDataDataSet
from .codat_public_api_models_data_data_set_paged_response_href_model import (
    CodatPublicApiModelsDataDataSetPagedResponseHrefModel,
)
from .codat_public_api_models_data_data_set_paged_response_links_model import (
    CodatPublicApiModelsDataDataSetPagedResponseLinksModel,
)
from .codat_public_api_models_data_data_set_paged_response_model import (
    CodatPublicApiModelsDataDataSetPagedResponseModel,
)
from .codat_public_api_models_data_data_status import CodatPublicApiModelsDataDataStatus
from .codat_public_api_models_data_dataset_status import CodatPublicApiModelsDataDatasetStatus
from .codat_public_api_models_data_profit_and_loss_response import CodatPublicApiModelsDataProfitAndLossResponse
from .codat_public_api_models_data_push_options_aggregate import CodatPublicApiModelsDataPushOptionsAggregate
from .codat_public_api_models_data_tracking_category import CodatPublicApiModelsDataTrackingCategory
from .codat_public_api_models_data_tracking_category_paged_response_href_model import (
    CodatPublicApiModelsDataTrackingCategoryPagedResponseHrefModel,
)
from .codat_public_api_models_data_tracking_category_paged_response_links_model import (
    CodatPublicApiModelsDataTrackingCategoryPagedResponseLinksModel,
)
from .codat_public_api_models_data_tracking_category_paged_response_model import (
    CodatPublicApiModelsDataTrackingCategoryPagedResponseModel,
)
from .codat_public_api_models_data_tracking_category_tree import CodatPublicApiModelsDataTrackingCategoryTree
from .codat_public_api_models_data_valid_datatype_links_response import (
    CodatPublicApiModelsDataValidDatatypeLinksResponse,
)
from .codat_public_api_models_file_metadata_model import CodatPublicApiModelsFileMetadataModel
from .codat_public_api_models_platform_credentials_data_provided_by import (
    CodatPublicApiModelsPlatformCredentialsDataProvidedBy,
)
from .codat_public_api_models_platform_credentials_datatype_features import (
    CodatPublicApiModelsPlatformCredentialsDatatypeFeatures,
)
from .codat_public_api_models_platform_credentials_enabled_args import (
    CodatPublicApiModelsPlatformCredentialsEnabledArgs,
)
from .codat_public_api_models_platform_credentials_integration_supported_environments import (
    CodatPublicApiModelsPlatformCredentialsIntegrationSupportedEnvironments,
)
from .codat_public_api_models_platform_credentials_platform_credentials import (
    CodatPublicApiModelsPlatformCredentialsPlatformCredentials,
)
from .codat_public_api_models_platform_credentials_platform_source_model import (
    CodatPublicApiModelsPlatformCredentialsPlatformSourceModel,
)
from .codat_public_api_models_platform_credentials_platform_source_model_paged_response_href_model import (
    CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseHrefModel,
)
from .codat_public_api_models_platform_credentials_platform_source_model_paged_response_links_model import (
    CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseLinksModel,
)
from .codat_public_api_models_platform_credentials_platform_source_model_paged_response_model import (
    CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel,
)
from .codat_public_api_models_platform_credentials_source_type import CodatPublicApiModelsPlatformCredentialsSourceType
from .codat_public_api_models_platform_credentials_supported_feature_state import (
    CodatPublicApiModelsPlatformCredentialsSupportedFeatureState,
)
from .codat_public_api_models_rules_add_rule_model import CodatPublicApiModelsRulesAddRuleModel
from .codat_public_api_models_rules_alert_model import CodatPublicApiModelsRulesAlertModel
from .codat_public_api_models_rules_alert_model_paged_response_href_model import (
    CodatPublicApiModelsRulesAlertModelPagedResponseHrefModel,
)
from .codat_public_api_models_rules_alert_model_paged_response_links_model import (
    CodatPublicApiModelsRulesAlertModelPagedResponseLinksModel,
)
from .codat_public_api_models_rules_alert_model_paged_response_model import (
    CodatPublicApiModelsRulesAlertModelPagedResponseModel,
)
from .codat_public_api_models_rules_notifiers import CodatPublicApiModelsRulesNotifiers
from .codat_public_api_models_rules_rule import CodatPublicApiModelsRulesRule
from .codat_public_api_models_rules_rule_paged_response_href_model import (
    CodatPublicApiModelsRulesRulePagedResponseHrefModel,
)
from .codat_public_api_models_rules_rule_paged_response_links_model import (
    CodatPublicApiModelsRulesRulePagedResponseLinksModel,
)
from .codat_public_api_models_rules_rule_paged_response_model import CodatPublicApiModelsRulesRulePagedResponseModel
from .codat_public_api_models_sync_settings_sync_setting_model import CodatPublicApiModelsSyncSettingsSyncSettingModel
from .codat_pull_messages_contracts_dataset_messages import CodatPullMessagesContractsDatasetMessages
from .codat_pull_messages_contracts_fetch_message import CodatPullMessagesContractsFetchMessage
from .codat_pull_messages_contracts_map_message import CodatPullMessagesContractsMapMessage
from .codat_pull_messages_contracts_validation_message import CodatPullMessagesContractsValidationMessage
from .codat_standard_reporting_contracts_i_dimension import CodatStandardReportingContractsIDimension
from .codat_standard_reporting_contracts_i_dimension_item import CodatStandardReportingContractsIDimensionItem
from .codat_standard_reporting_contracts_i_report_data_measure import CodatStandardReportingContractsIReportDataMeasure
from .codat_standard_reporting_contracts_measure import CodatStandardReportingContractsMeasure
from .codat_standard_reporting_contracts_report import CodatStandardReportingContractsReport
from .codat_standard_reporting_contracts_report_data import CodatStandardReportingContractsReportData
from .codat_standard_reporting_contracts_report_error import CodatStandardReportingContractsReportError
from .codat_standard_reporting_contracts_report_error_details import CodatStandardReportingContractsReportErrorDetails
from .codat_standard_reporting_contracts_report_error_type import CodatStandardReportingContractsReportErrorType
from .codat_standard_reporting_contracts_report_report_info import CodatStandardReportingContractsReportReportInfo
from .codat_standardization_bank_feeds_accounts_contract_bank_feed_bank_account import (
    CodatStandardizationBankFeedsAccountsContractBankFeedBankAccount,
)
from .get_companies_company_id_data_status_response_200 import GetCompaniesCompanyIdDataStatusResponse200
from .patch_companies_company_id_connections_connection_id_json_body import (
    PatchCompaniesCompanyIdConnectionsConnectionIdJsonBody,
)
from .post_companies_company_id_connections_json_body import PostCompaniesCompanyIdConnectionsJsonBody
from .put_companies_company_id_connections_connection_id_authorization_json_body import (
    PutCompaniesCompanyIdConnectionsConnectionIdAuthorizationJsonBody,
)
from .put_integrations_credentials_platform_key_json_body import PutIntegrationsCredentialsPlatformKeyJsonBody
from .system_object_push_operation import SystemObjectPushOperation
from .system_object_push_operation_paged_response_href_model import SystemObjectPushOperationPagedResponseHrefModel
from .system_object_push_operation_paged_response_links_model import SystemObjectPushOperationPagedResponseLinksModel
from .system_object_push_operation_paged_response_model import SystemObjectPushOperationPagedResponseModel

__all__ = (
    "CodatAssessDataContractsAccountCategoriesAccountCategoriesModel",
    "CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseHrefModel",
    "CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseLinksModel",
    "CodatAssessDataContractsAccountCategoriesAccountCategoriesModelPagedResponseModel",
    "CodatAssessDataContractsAccountCategoriesAccountCategory",
    "CodatAssessDataContractsAccountCategoriesAccountRefModel",
    "CodatAssessDataContractsAccountCategoriesConfirmedAccountCategoryModel",
    "CodatAssessDataContractsAccountCategoriesPatchAccountCategoriesModel",
    "CodatAssessDataContractsAccountCategoriesPatchAccountCategoryModel",
    "CodatAssessDataContractsAccountCategoriesPatchAccountRefModel",
    "CodatAssessDataContractsAccountCategoriesPatchSingleAccountCategoryModel",
    "CodatAssessDataContractsAccountCategoriesSuggestedAccountCategoryModel",
    "CodatAssessDataContractsCashFlowTransactionsAccountsDataSource",
    "CodatAssessDataContractsCashFlowTransactionsCashFlowReportBankingAccount",
    "CodatAssessDataContractsCashFlowTransactionsCashFlowReportBankingTransaction",
    "CodatAssessDataContractsCashFlowTransactionsCashFlowTransactionsReport",
    "CodatAssessDataContractsCashFlowTransactionsSourceRef",
    "CodatAssessDataContractsCashFlowTransactionsSourceType",
    "CodatAssessDataContractsCashFlowTransactionsTransactionCategory",
    "CodatAssessDataContractsCashFlowTransactionsTransactionsDataSource",
    "CodatAssessDataContractsCommerceMetricsPeriodUnit",
    "CodatAssessDataContractsCommonPagedReportInfo",
    "CodatAssessDataContractsFinancialsMetricsFinancialMetricsDataSet",
    "CodatAssessDataContractsFinancialsMetricsMetric",
    "CodatAssessDataContractsFinancialsMetricsMetricDataSetError",
    "CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorType",
    "CodatAssessDataContractsFinancialsMetricsMetricError",
    "CodatAssessDataContractsFinancialsMetricsMetricErrorDetails",
    "CodatAssessDataContractsFinancialsMetricsMetricErrorType",
    "CodatAssessDataContractsFinancialsMetricsMetricKey",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriod",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriodError",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorDetails",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorType",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriodInput",
    "CodatAssessDataContractsFinancialsMetricsMetricPeriodUnit",
    "CodatAssessDataContractsFinancialsMetricsMetricUnit",
    "CodatAssessDataContractsFinancialsStatementsAccountCategory",
    "CodatAssessDataContractsFinancialsStatementsAccountCategoryLevel",
    "CodatAssessDataContractsFinancialsStatementsAccountCategoryStatus",
    "CodatAssessDataContractsFinancialsStatementsEnhancedFinancialStatement",
    "CodatAssessDataContractsFinancialsStatementsFinancialStatementReportInfo",
    "CodatAssessDataContractsFinancialsStatementsFinancialStatementReportItem",
    "CodatClientsApiClientContractClientSyncSettings",
    "CodatClientsApiClientContractCompanySettings",
    "CodatClientsApiClientContractCompanySyncSettings",
    "CodatClientsApiClientContractSyncSetting",
    "CodatDataContractsDatasetsAccount",
    "CodatDataContractsDatasetsAccountPagedResponseHrefModel",
    "CodatDataContractsDatasetsAccountPagedResponseLinksModel",
    "CodatDataContractsDatasetsAccountPagedResponseModel",
    "CodatDataContractsDatasetsAccountPushOperation",
    "CodatDataContractsDatasetsAccountRef",
    "CodatDataContractsDatasetsAccountsPayableIsBilledToType",
    "CodatDataContractsDatasetsAccountsPayableTracking",
    "CodatDataContractsDatasetsAccountsReceivableIsBilledToType",
    "CodatDataContractsDatasetsAccountsReceivableTracking",
    "CodatDataContractsDatasetsAccountStatus",
    "CodatDataContractsDatasetsAccountTransaction",
    "CodatDataContractsDatasetsAccountTransactionLine",
    "CodatDataContractsDatasetsAccountTransactionPagedResponse",
    "CodatDataContractsDatasetsAccountTransactionPagedResponseLinks",
    "CodatDataContractsDatasetsAccountTransactionStatus",
    "CodatDataContractsDatasetsAccountType",
    "CodatDataContractsDatasetsAddress",
    "CodatDataContractsDatasetsAddressType",
    "CodatDataContractsDatasetsAgedCreditorOutstanding",
    "CodatDataContractsDatasetsAgedCreditorOutstandingICollectionReport",
    "CodatDataContractsDatasetsAgedCurrencyOutstanding",
    "CodatDataContractsDatasetsAgedDebtorOutstanding",
    "CodatDataContractsDatasetsAgedDebtorOutstandingICollectionReport",
    "CodatDataContractsDatasetsAgedOutstandingAmount",
    "CodatDataContractsDatasetsAgedOutstandingAmountDetail",
    "CodatDataContractsDatasetsAllocation",
    "CodatDataContractsDatasetsAttachmentsDataset",
    "CodatDataContractsDatasetsAttachmentsDatasetAttachment",
    "CodatDataContractsDatasetsBalanceSheet",
    "CodatDataContractsDatasetsBankAccount",
    "CodatDataContractsDatasetsBankAccountPagedResponseHrefModel",
    "CodatDataContractsDatasetsBankAccountPagedResponseLinksModel",
    "CodatDataContractsDatasetsBankAccountPagedResponseModel",
    "CodatDataContractsDatasetsBankAccountPushOperation",
    "CodatDataContractsDatasetsBankAccountType",
    "CodatDataContractsDatasetsBankingAccount",
    "CodatDataContractsDatasetsBankingAccountBalance",
    "CodatDataContractsDatasetsBankingAccountBalanceAmounts",
    "CodatDataContractsDatasetsBankingAccountBalancePagedResponseHrefModel",
    "CodatDataContractsDatasetsBankingAccountBalancePagedResponseLinksModel",
    "CodatDataContractsDatasetsBankingAccountBalancePagedResponseModel",
    "CodatDataContractsDatasetsBankingAccountIdentifiers",
    "CodatDataContractsDatasetsBankingAccountInstitution",
    "CodatDataContractsDatasetsBankingAccountPagedResponseHrefModel",
    "CodatDataContractsDatasetsBankingAccountPagedResponseLinksModel",
    "CodatDataContractsDatasetsBankingAccountPagedResponseModel",
    "CodatDataContractsDatasetsBankingAccountType",
    "CodatDataContractsDatasetsBankingBankingTransactionCode",
    "CodatDataContractsDatasetsBankingTransaction",
    "CodatDataContractsDatasetsBankingTransactionCategory",
    "CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseHrefModel",
    "CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseLinksModel",
    "CodatDataContractsDatasetsBankingTransactionCategoryPagedResponseModel",
    "CodatDataContractsDatasetsBankingTransactionCategoryRef",
    "CodatDataContractsDatasetsBankingTransactionCategoryStatus",
    "CodatDataContractsDatasetsBankingTransactionPagedResponseHrefModel",
    "CodatDataContractsDatasetsBankingTransactionPagedResponseLinksModel",
    "CodatDataContractsDatasetsBankingTransactionPagedResponseModel",
    "CodatDataContractsDatasetsBankStatementAccount",
    "CodatDataContractsDatasetsBankStatementLine",
    "CodatDataContractsDatasetsBankStatementLinePagedResponseHrefModel",
    "CodatDataContractsDatasetsBankStatementLinePagedResponseLinksModel",
    "CodatDataContractsDatasetsBankStatementLinePagedResponseModel",
    "CodatDataContractsDatasetsBankTransaction",
    "CodatDataContractsDatasetsBankTransactionPagedResponseHrefModel",
    "CodatDataContractsDatasetsBankTransactionPagedResponseLinksModel",
    "CodatDataContractsDatasetsBankTransactionPagedResponseModel",
    "CodatDataContractsDatasetsBankTransactions",
    "CodatDataContractsDatasetsBankTransactionsPushOperation",
    "CodatDataContractsDatasetsBill",
    "CodatDataContractsDatasetsBillCreditNote",
    "CodatDataContractsDatasetsBillCreditNoteLineItem",
    "CodatDataContractsDatasetsBillCreditNotePagedResponseHrefModel",
    "CodatDataContractsDatasetsBillCreditNotePagedResponseLinksModel",
    "CodatDataContractsDatasetsBillCreditNotePagedResponseModel",
    "CodatDataContractsDatasetsBillCreditNotePushOperation",
    "CodatDataContractsDatasetsBillItem",
    "CodatDataContractsDatasetsBillLineItem",
    "CodatDataContractsDatasetsBillPagedResponseHrefModel",
    "CodatDataContractsDatasetsBillPagedResponseLinksModel",
    "CodatDataContractsDatasetsBillPagedResponseModel",
    "CodatDataContractsDatasetsBillPayment",
    "CodatDataContractsDatasetsBillPaymentLine",
    "CodatDataContractsDatasetsBillPaymentLineLink",
    "CodatDataContractsDatasetsBillPaymentLinkType",
    "CodatDataContractsDatasetsBillPaymentPagedResponseHrefModel",
    "CodatDataContractsDatasetsBillPaymentPagedResponseLinksModel",
    "CodatDataContractsDatasetsBillPaymentPagedResponseModel",
    "CodatDataContractsDatasetsBillPaymentPushOperation",
    "CodatDataContractsDatasetsBillPushOperation",
    "CodatDataContractsDatasetsBillStatus",
    "CodatDataContractsDatasetsCashFlowStatement",
    "CodatDataContractsDatasetsCashFlowStatementReportingBasis",
    "CodatDataContractsDatasetsCashFlowStatementReportingData",
    "CodatDataContractsDatasetsCommerceAccountBalance",
    "CodatDataContractsDatasetsCommerceAddress",
    "CodatDataContractsDatasetsCommerceAddressType",
    "CodatDataContractsDatasetsCommerceAncestorRef",
    "CodatDataContractsDatasetsCommerceCompanyInfo",
    "CodatDataContractsDatasetsCommerceCompanyInfoSourceUrls",
    "CodatDataContractsDatasetsCommerceCustomer",
    "CodatDataContractsDatasetsCommerceCustomerPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceCustomerPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceCustomerPagedResponseModel",
    "CodatDataContractsDatasetsCommerceCustomerRef",
    "CodatDataContractsDatasetsCommerceDiscountAllocation",
    "CodatDataContractsDatasetsCommerceDispute",
    "CodatDataContractsDatasetsCommerceDisputePagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceDisputePagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceDisputePagedResponseModel",
    "CodatDataContractsDatasetsCommerceDisputeStatus",
    "CodatDataContractsDatasetsCommerceInventory",
    "CodatDataContractsDatasetsCommerceInventoryLocation",
    "CodatDataContractsDatasetsCommerceLocation",
    "CodatDataContractsDatasetsCommerceLocationPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceLocationPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceLocationPagedResponseModel",
    "CodatDataContractsDatasetsCommerceLocationRef",
    "CodatDataContractsDatasetsCommerceOrder",
    "CodatDataContractsDatasetsCommerceOrderLineItem",
    "CodatDataContractsDatasetsCommerceOrderPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceOrderPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceOrderPagedResponseModel",
    "CodatDataContractsDatasetsCommercePayment",
    "CodatDataContractsDatasetsCommercePaymentMethod",
    "CodatDataContractsDatasetsCommercePaymentMethodPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommercePaymentMethodPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommercePaymentMethodPagedResponseModel",
    "CodatDataContractsDatasetsCommercePaymentMethodRef",
    "CodatDataContractsDatasetsCommercePaymentMethodStatus",
    "CodatDataContractsDatasetsCommercePaymentPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommercePaymentPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommercePaymentPagedResponseModel",
    "CodatDataContractsDatasetsCommercePaymentRef",
    "CodatDataContractsDatasetsCommercePaymentStatus",
    "CodatDataContractsDatasetsCommercePaymentType",
    "CodatDataContractsDatasetsCommercePhone",
    "CodatDataContractsDatasetsCommercePhoneType",
    "CodatDataContractsDatasetsCommercePlatformTransactionType",
    "CodatDataContractsDatasetsCommerceProduct",
    "CodatDataContractsDatasetsCommerceProductCategory",
    "CodatDataContractsDatasetsCommerceProductCategoryPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceProductCategoryPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceProductCategoryPagedResponseModel",
    "CodatDataContractsDatasetsCommerceProductCategoryRef",
    "CodatDataContractsDatasetsCommerceProductPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceProductPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceProductPagedResponseModel",
    "CodatDataContractsDatasetsCommerceProductRef",
    "CodatDataContractsDatasetsCommerceProductStatus",
    "CodatDataContractsDatasetsCommerceProductVariant",
    "CodatDataContractsDatasetsCommerceProductVariantPrice",
    "CodatDataContractsDatasetsCommerceServiceCharge",
    "CodatDataContractsDatasetsCommerceServiceChargeType",
    "CodatDataContractsDatasetsCommerceTaxComponentAllocation",
    "CodatDataContractsDatasetsCommerceTaxComponentRef",
    "CodatDataContractsDatasetsCommerceTransaction",
    "CodatDataContractsDatasetsCommerceTransactionPagedResponseHrefModel",
    "CodatDataContractsDatasetsCommerceTransactionPagedResponseLinksModel",
    "CodatDataContractsDatasetsCommerceTransactionPagedResponseModel",
    "CodatDataContractsDatasetsCommerceTransactionRefType",
    "CodatDataContractsDatasetsCommerceTransactionSourceRef",
    "CodatDataContractsDatasetsCommerceWebLink",
    "CodatDataContractsDatasetsCommerceWebLinkType",
    "CodatDataContractsDatasetsCompanyDataset",
    "CodatDataContractsDatasetsCompanyDatasetSourceUrls",
    "CodatDataContractsDatasetsContact",
    "CodatDataContractsDatasetsContactRef",
    "CodatDataContractsDatasetsCreditNote",
    "CodatDataContractsDatasetsCreditNoteLineItem",
    "CodatDataContractsDatasetsCreditNotePagedResponseHrefModel",
    "CodatDataContractsDatasetsCreditNotePagedResponseLinksModel",
    "CodatDataContractsDatasetsCreditNotePagedResponseModel",
    "CodatDataContractsDatasetsCreditNotePushOperation",
    "CodatDataContractsDatasetsCreditNoteStatus",
    "CodatDataContractsDatasetsCustomer",
    "CodatDataContractsDatasetsCustomerPagedResponseHrefModel",
    "CodatDataContractsDatasetsCustomerPagedResponseLinksModel",
    "CodatDataContractsDatasetsCustomerPagedResponseModel",
    "CodatDataContractsDatasetsCustomerPushOperation",
    "CodatDataContractsDatasetsCustomerRef",
    "CodatDataContractsDatasetsCustomerStatus",
    "CodatDataContractsDatasetsDataInterfacesSupplementalData",
    "CodatDataContractsDatasetsDataInterfacesSupplementalDataContent",
    "CodatDataContractsDatasetsDataInterfacesSupplementalDataContentAdditionalProperty",
    "CodatDataContractsDatasetsDetailedPaymentAllocation",
    "CodatDataContractsDatasetsDirectCost",
    "CodatDataContractsDatasetsDirectCostLineItem",
    "CodatDataContractsDatasetsDirectCostPagedResponseHrefModel",
    "CodatDataContractsDatasetsDirectCostPagedResponseLinksModel",
    "CodatDataContractsDatasetsDirectCostPagedResponseModel",
    "CodatDataContractsDatasetsDirectCostPushOperation",
    "CodatDataContractsDatasetsDirectIncome",
    "CodatDataContractsDatasetsDirectIncomeLineItem",
    "CodatDataContractsDatasetsDirectIncomePagedResponseHrefModel",
    "CodatDataContractsDatasetsDirectIncomePagedResponseLinksModel",
    "CodatDataContractsDatasetsDirectIncomePagedResponseModel",
    "CodatDataContractsDatasetsDirectIncomePushOperation",
    "CodatDataContractsDatasetsFromAccount",
    "CodatDataContractsDatasetsInvoice",
    "CodatDataContractsDatasetsInvoiceableTracking",
    "CodatDataContractsDatasetsInvoiceItem",
    "CodatDataContractsDatasetsInvoiceLineItem",
    "CodatDataContractsDatasetsInvoicePagedResponseHrefModel",
    "CodatDataContractsDatasetsInvoicePagedResponseLinksModel",
    "CodatDataContractsDatasetsInvoicePagedResponseModel",
    "CodatDataContractsDatasetsInvoicePushOperation",
    "CodatDataContractsDatasetsInvoiceStatus",
    "CodatDataContractsDatasetsInvoicingStatus",
    "CodatDataContractsDatasetsItem",
    "CodatDataContractsDatasetsItemPagedResponseHrefModel",
    "CodatDataContractsDatasetsItemPagedResponseLinksModel",
    "CodatDataContractsDatasetsItemPagedResponseModel",
    "CodatDataContractsDatasetsItemPushOperation",
    "CodatDataContractsDatasetsItemRef",
    "CodatDataContractsDatasetsItemStatus",
    "CodatDataContractsDatasetsItemType",
    "CodatDataContractsDatasetsJournal",
    "CodatDataContractsDatasetsJournalEntry",
    "CodatDataContractsDatasetsJournalEntryPagedResponseHrefModel",
    "CodatDataContractsDatasetsJournalEntryPagedResponseLinksModel",
    "CodatDataContractsDatasetsJournalEntryPagedResponseModel",
    "CodatDataContractsDatasetsJournalEntryPushOperation",
    "CodatDataContractsDatasetsJournalLine",
    "CodatDataContractsDatasetsJournalPagedResponseHrefModel",
    "CodatDataContractsDatasetsJournalPagedResponseLinksModel",
    "CodatDataContractsDatasetsJournalPagedResponseModel",
    "CodatDataContractsDatasetsJournalPushOperation",
    "CodatDataContractsDatasetsJournalRef",
    "CodatDataContractsDatasetsJournalStatus",
    "CodatDataContractsDatasetsMetadata",
    "CodatDataContractsDatasetsPayment",
    "CodatDataContractsDatasetsPaymentAllocationPayment",
    "CodatDataContractsDatasetsPaymentLine",
    "CodatDataContractsDatasetsPaymentLineLink",
    "CodatDataContractsDatasetsPaymentLinkType",
    "CodatDataContractsDatasetsPaymentMethod",
    "CodatDataContractsDatasetsPaymentMethodPagedResponseHrefModel",
    "CodatDataContractsDatasetsPaymentMethodPagedResponseLinksModel",
    "CodatDataContractsDatasetsPaymentMethodPagedResponseModel",
    "CodatDataContractsDatasetsPaymentMethodRef",
    "CodatDataContractsDatasetsPaymentMethodStatus",
    "CodatDataContractsDatasetsPaymentMethodType",
    "CodatDataContractsDatasetsPaymentPagedResponseHrefModel",
    "CodatDataContractsDatasetsPaymentPagedResponseLinksModel",
    "CodatDataContractsDatasetsPaymentPagedResponseModel",
    "CodatDataContractsDatasetsPaymentPushOperation",
    "CodatDataContractsDatasetsPhone",
    "CodatDataContractsDatasetsPhoneType",
    "CodatDataContractsDatasetsProfitAndLossReport",
    "CodatDataContractsDatasetsProfitAndLossReportingType",
    "CodatDataContractsDatasetsProjectRef",
    "CodatDataContractsDatasetsPurchaseOrder",
    "CodatDataContractsDatasetsPurchaseOrderLineItem",
    "CodatDataContractsDatasetsPurchaseOrderPagedResponseHrefModel",
    "CodatDataContractsDatasetsPurchaseOrderPagedResponseLinksModel",
    "CodatDataContractsDatasetsPurchaseOrderPagedResponseModel",
    "CodatDataContractsDatasetsPurchaseOrderPushOperation",
    "CodatDataContractsDatasetsPurchaseOrderRef",
    "CodatDataContractsDatasetsPurchaseOrderStatus",
    "CodatDataContractsDatasetsRecordRef",
    "CodatDataContractsDatasetsReportLine",
    "CodatDataContractsDatasetsSalesOrder",
    "CodatDataContractsDatasetsSalesOrderLineItem",
    "CodatDataContractsDatasetsSalesOrderPagedResponseHrefModel",
    "CodatDataContractsDatasetsSalesOrderPagedResponseLinksModel",
    "CodatDataContractsDatasetsSalesOrderPagedResponseModel",
    "CodatDataContractsDatasetsSalesOrderStatus",
    "CodatDataContractsDatasetsShipTo",
    "CodatDataContractsDatasetsShipToContact",
    "CodatDataContractsDatasetsSupplier",
    "CodatDataContractsDatasetsSupplierPagedResponseHrefModel",
    "CodatDataContractsDatasetsSupplierPagedResponseLinksModel",
    "CodatDataContractsDatasetsSupplierPagedResponseModel",
    "CodatDataContractsDatasetsSupplierPushOperation",
    "CodatDataContractsDatasetsSupplierRef",
    "CodatDataContractsDatasetsSupplierStatus",
    "CodatDataContractsDatasetsTaxRate",
    "CodatDataContractsDatasetsTaxRateComponent",
    "CodatDataContractsDatasetsTaxRatePagedResponseHrefModel",
    "CodatDataContractsDatasetsTaxRatePagedResponseLinksModel",
    "CodatDataContractsDatasetsTaxRatePagedResponseModel",
    "CodatDataContractsDatasetsTaxRateRef",
    "CodatDataContractsDatasetsTaxRateStatus",
    "CodatDataContractsDatasetsToAccount",
    "CodatDataContractsDatasetsTracking",
    "CodatDataContractsDatasetsTrackingCategoryRef",
    "CodatDataContractsDatasetsTrackingCategoryStatus",
    "CodatDataContractsDatasetsTransactionType",
    "CodatDataContractsDatasetsTransfer",
    "CodatDataContractsDatasetsTransferPagedResponseHrefModel",
    "CodatDataContractsDatasetsTransferPagedResponseLinksModel",
    "CodatDataContractsDatasetsTransferPagedResponseModel",
    "CodatDataContractsDatasetsTransferPushOperation",
    "CodatDataContractsDatasetsTransferStatus",
    "CodatDataContractsDatasetsValidDatatypeLinks",
    "CodatDataContractsDatasetsWebLink",
    "CodatDataContractsDatasetsWebLinkType",
    "CodatDataContractsDatasetsWithholdingTax",
    "CodatDataContractsPushOptionType",
    "CodatDataContractsPushPushChangeType",
    "CodatDataContractsPushPushFieldValidation",
    "CodatDataContractsPushPushOperationChange",
    "CodatDataContractsPushPushOperationRecordRef",
    "CodatDataContractsPushPushOption",
    "CodatDataContractsPushPushOptionChoice",
    "CodatDataContractsPushPushOptionChoiceProperties",
    "CodatDataContractsPushPushOptionProperties",
    "CodatDataContractsPushPushValidationInfo",
    "CodatDataContractsResponsesHalLink",
    "CodatDataContractsValidationValidationItem",
    "CodatDataContractsValidationValidationResult",
    "CodatDataIntegrityContractsDetailsTransactionDetails",
    "CodatDataIntegrityContractsDetailsTransactionDetailsPagedResponse",
    "CodatDataIntegrityContractsDetailsTransactionDetailsPagedResponseLinks",
    "CodatDataIntegrityContractsMetadataMatchAmountInfo",
    "CodatDataIntegrityContractsMetadataMatchConnectionIds",
    "CodatDataIntegrityContractsMetadataMatchDateInfo",
    "CodatDataIntegrityContractsMetadataMatchMetadata",
    "CodatDataIntegrityContractsMetadataMatchMetadataResponse",
    "CodatDataIntegrityContractsMetadataMatchStatusInfo",
    "CodatDataIntegrityContractsMetadataRunStatus",
    "CodatDataIntegrityContractsSummaryMatchAmountSummary",
    "CodatDataIntegrityContractsSummaryMatchCountSummary",
    "CodatDataIntegrityContractsSummaryMatchSummariesResponse",
    "CodatDataIntegrityContractsSummaryMatchSummary",
    "CodatPublicApiModelsAssessAssessExcelMeta",
    "CodatPublicApiModelsClientsBankingSettingsModelsBankIntegration",
    "CodatPublicApiModelsClientsBankingSettingsModelsBankSetting",
    "CodatPublicApiModelsClientsBankingSettingsModelsBankSettingsDataset",
    "CodatPublicApiModelsClientsClientCompanyMetricsModel",
    "CodatPublicApiModelsClientsClientSettingsModel",
    "CodatPublicApiModelsClientsClientSettingsPatchModel",
    "CodatPublicApiModelsClientsClientSyncSettingsModel",
    "CodatPublicApiModelsClientsClientSyncSettingsSinglePutModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelButtonModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelDefaultModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelFullModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelHoverModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelImageModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelLogoModel",
    "CodatPublicApiModelsClientsIntegrationBrandingModelSquareModel",
    "CodatPublicApiModelsClientsIntegrationSettingsModel",
    "CodatPublicApiModelsClientsIntegrationSettingsPatchModel",
    "CodatPublicApiModelsCompanyAddCompanyModel",
    "CodatPublicApiModelsCompanyCompany",
    "CodatPublicApiModelsCompanyCompanyEventStream",
    "CodatPublicApiModelsCompanyCompanyEventStreamItem",
    "CodatPublicApiModelsCompanyCompanyPagedResponseHrefModel",
    "CodatPublicApiModelsCompanyCompanyPagedResponseLinksModel",
    "CodatPublicApiModelsCompanyCompanyPagedResponseModel",
    "CodatPublicApiModelsCompanyCompanySettings",
    "CodatPublicApiModelsCompanyDataConnection",
    "CodatPublicApiModelsCompanyDataConnectionConnectionInfo",
    "CodatPublicApiModelsCompanyDataConnectionError",
    "CodatPublicApiModelsCompanyDataConnectionPagedResponseHrefModel",
    "CodatPublicApiModelsCompanyDataConnectionPagedResponseLinksModel",
    "CodatPublicApiModelsCompanyDataConnectionPagedResponseModel",
    "CodatPublicApiModelsCompanyPatchDataConnectionModel",
    "CodatPublicApiModelsCompanyPatchDataConnectionModelConnectionInfo",
    "CodatPublicApiModelsCompanyProfileModel",
    "CodatPublicApiModelsCompanyUpdateCompanyModel",
    "CodatPublicApiModelsDataAccountResponse",
    "CodatPublicApiModelsDataAccountStatusResponse",
    "CodatPublicApiModelsDataAccountTypeResponse",
    "CodatPublicApiModelsDataBalanceSheetResponse",
    "CodatPublicApiModelsDataCashFlowStatementResponse",
    "CodatPublicApiModelsDataDataSet",
    "CodatPublicApiModelsDataDataSetPagedResponseHrefModel",
    "CodatPublicApiModelsDataDataSetPagedResponseLinksModel",
    "CodatPublicApiModelsDataDataSetPagedResponseModel",
    "CodatPublicApiModelsDataDatasetStatus",
    "CodatPublicApiModelsDataDataStatus",
    "CodatPublicApiModelsDataProfitAndLossResponse",
    "CodatPublicApiModelsDataPushOptionsAggregate",
    "CodatPublicApiModelsDataTrackingCategory",
    "CodatPublicApiModelsDataTrackingCategoryPagedResponseHrefModel",
    "CodatPublicApiModelsDataTrackingCategoryPagedResponseLinksModel",
    "CodatPublicApiModelsDataTrackingCategoryPagedResponseModel",
    "CodatPublicApiModelsDataTrackingCategoryTree",
    "CodatPublicApiModelsDataValidDatatypeLinksResponse",
    "CodatPublicApiModelsFileMetadataModel",
    "CodatPublicApiModelsPlatformCredentialsDataProvidedBy",
    "CodatPublicApiModelsPlatformCredentialsDatatypeFeatures",
    "CodatPublicApiModelsPlatformCredentialsEnabledArgs",
    "CodatPublicApiModelsPlatformCredentialsIntegrationSupportedEnvironments",
    "CodatPublicApiModelsPlatformCredentialsPlatformCredentials",
    "CodatPublicApiModelsPlatformCredentialsPlatformSourceModel",
    "CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseHrefModel",
    "CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseLinksModel",
    "CodatPublicApiModelsPlatformCredentialsPlatformSourceModelPagedResponseModel",
    "CodatPublicApiModelsPlatformCredentialsSourceType",
    "CodatPublicApiModelsPlatformCredentialsSupportedFeatureState",
    "CodatPublicApiModelsRulesAddRuleModel",
    "CodatPublicApiModelsRulesAlertModel",
    "CodatPublicApiModelsRulesAlertModelPagedResponseHrefModel",
    "CodatPublicApiModelsRulesAlertModelPagedResponseLinksModel",
    "CodatPublicApiModelsRulesAlertModelPagedResponseModel",
    "CodatPublicApiModelsRulesNotifiers",
    "CodatPublicApiModelsRulesRule",
    "CodatPublicApiModelsRulesRulePagedResponseHrefModel",
    "CodatPublicApiModelsRulesRulePagedResponseLinksModel",
    "CodatPublicApiModelsRulesRulePagedResponseModel",
    "CodatPublicApiModelsSyncSettingsSyncSettingModel",
    "CodatPullMessagesContractsDatasetMessages",
    "CodatPullMessagesContractsFetchMessage",
    "CodatPullMessagesContractsMapMessage",
    "CodatPullMessagesContractsValidationMessage",
    "CodatStandardizationBankFeedsAccountsContractBankFeedBankAccount",
    "CodatStandardReportingContractsIDimension",
    "CodatStandardReportingContractsIDimensionItem",
    "CodatStandardReportingContractsIReportDataMeasure",
    "CodatStandardReportingContractsMeasure",
    "CodatStandardReportingContractsReport",
    "CodatStandardReportingContractsReportData",
    "CodatStandardReportingContractsReportError",
    "CodatStandardReportingContractsReportErrorDetails",
    "CodatStandardReportingContractsReportErrorType",
    "CodatStandardReportingContractsReportReportInfo",
    "GetCompaniesCompanyIdDataStatusResponse200",
    "PatchCompaniesCompanyIdConnectionsConnectionIdJsonBody",
    "PostCompaniesCompanyIdConnectionsJsonBody",
    "PutCompaniesCompanyIdConnectionsConnectionIdAuthorizationJsonBody",
    "PutIntegrationsCredentialsPlatformKeyJsonBody",
    "SystemObjectPushOperation",
    "SystemObjectPushOperationPagedResponseHrefModel",
    "SystemObjectPushOperationPagedResponseLinksModel",
    "SystemObjectPushOperationPagedResponseModel",
)
